### ISSUE TITLE
removeTag not Working

### ISSUE THREAD

**Issue by anjusr** [pulimento/TagListView-ObjC#4] opened 2016-11-09 07:08 UTC
i couldn't remove the tag from tagListView by using this line [tagListView removeTag:@"meow"];

**Comment by anjusr** [comment] 2016-11-09 09:03
Ok, Got it.. it should be index >= 0 in for-loop condition inside removeTag method.

**Comment by pulimento** [comment] 2016-11-09 13:12
If you are so kind, please made me a pull request and I accept it. Thanks
in advance

2016-11-09 10:03 GMT+01:00 anjusr notifications@github.com:

> Ok, Got it.. it should be index >= 0 in for-loop condition inside
> removeTag method.

**Comment by pulimento** [comment] 2017-04-11 10:31
Seems that you are OK now, I'm closing this issue. Please let me know if the issue is not solved

**Closed as completed** 2017-04-11 10:31 UTC
Labels: help wanted
